name: Publise to NPM
on:
  push:
    branches:
      - master
jobs:
  publish-to-npm:

    runs-on: ubuntu-latest

    steps:
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
